name: Build CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build (${{ matrix.goos }}/${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: windows
            goarch: 386

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: build-cli
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build-cli

  package:
    name: validate-plugin-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install mingw-w64
        run: sudo apt-get install -y gcc-mingw-w64-i686

      - name: validate-plugin-package
        run: make validate-plugin-package
